// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv8T4_anzQL14YP_BdsJd4_prFFfFRvA8',
    appId: '1:959495157119:web:1ae8B77bfc7d0adb1cd64a',
    messagingSenderId: '959495157119',
    projectId: 'gym-trainer-app-54867',
    authDomain: 'gym-trainer-app-54867.firebaseapp.com',
    storageBucket: 'gym-trainer-app-54867.firebasestorage.app',
    measurementId: 'G-T973SPNB8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'your-android-api-key-here',
    appId: 'your-android-app-id-here',
    messagingSenderId: 'your-sender-id-here',
    projectId: 'your-project-id-here',
    storageBucket: 'your-project-id-here.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your-ios-api-key-here',
    appId: 'your-ios-app-id-here',
    messagingSenderId: 'your-sender-id-here',
    projectId: 'your-project-id-here',
    storageBucket: 'your-project-id-here.appspot.com',
    iosBundleId: 'com.example.gymTrainerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your-ios-api-key-here',
    appId: 'your-ios-app-id-here',
    messagingSenderId: 'your-sender-id-here',
    projectId: 'your-project-id-here',
    storageBucket: 'your-project-id-here.appspot.com',
    iosBundleId: 'com.example.gymTrainerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'your-api-key-here',
    appId: 'your-app-id-here',
    messagingSenderId: 'your-sender-id-here',
    projectId: 'your-project-id-here',
    authDomain: 'your-project-id-here.firebaseapp.com',
    storageBucket: 'your-project-id-here.appspot.com',
  );
}